local opt = vim.opt

opt.encoding = "utf-8"
opt.fileencoding = "utf-8"
opt.number= true
opt.relativenumber = true
opt.title = true
opt.autoindent = true
opt.smartindent = true
opt.hlsearch = true
opt.backup = false
opt.showcmd = true
opt.cmdheight = 1
opt.laststatus = 3
opt.expandtab = true
opt.tabstop = 4
opt.shiftwidth=0
opt.softtabstop=0
opt.mouse = ""
opt.smarttab = true
opt.termguicolors = true
